export interface FoodItem {
  id: string;
  name: string;
  category: "PROTEIN" | "CARB" | "FAT" | "VEGETABLE";
  serving: string;
  servingGrams: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  fdcId?: string;
  source: string;
}

// Curated USDA FoodData Central (Foundation & SR Legacy) Reference Standards
export const USDA_REFERENCE_FOODS: FoodItem[] = [
  // Proteins
  {
    id: "usda-171077",
    name: "Boneless Skinless Chicken Breast (Cooked, Roasted)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    fiber: 0.0,
    fdcId: "171077",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-173686",
    name: "Wild Atlantic Salmon (Cooked, Dry Heat)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 182,
    protein: 25.4,
    carbs: 0.0,
    fat: 8.1,
    fiber: 0.0,
    fdcId: "173686",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-173424",
    name: "Egg Whites (Cooked)",
    category: "PROTEIN",
    serving: "100g (~3 large whites)",
    servingGrams: 100,
    calories: 52,
    protein: 10.9,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0.0,
    fdcId: "173424",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170886",
    name: "Nonfat Plain Greek Yogurt (0% Fat)",
    category: "PROTEIN",
    serving: "170g (1 container)",
    servingGrams: 170,
    calories: 100,
    protein: 17.3,
    carbs: 6.1,
    fat: 0.7,
    fiber: 0.0,
    fdcId: "170886",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-174036",
    name: "Lean Ground Turkey (93% Lean / 7% Fat)",
    category: "PROTEIN",
    serving: "112g (4 oz)",
    servingGrams: 112,
    calories: 170,
    protein: 21.0,
    carbs: 0.0,
    fat: 9.0,
    fiber: 0.0,
    fdcId: "174036",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-172449",
    name: "Extra Firm Tofu (Prepared with Nigari)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 83,
    protein: 10.0,
    carbs: 1.2,
    fat: 5.3,
    fiber: 0.9,
    fdcId: "172449",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-175158",
    name: "Whey Protein Isolate (Standard 90%)",
    category: "PROTEIN",
    serving: "30g (1 scoop)",
    servingGrams: 30,
    calories: 110,
    protein: 25.0,
    carbs: 1.0,
    fat: 0.5,
    fiber: 0.0,
    fdcId: "175158",
    source: "USDA FoodData Central (Branded & Foundation)",
  },

  // Carbohydrates
  {
    id: "usda-168878",
    name: "Rolled Oats (Dry, Whole Grain)",
    category: "CARB",
    serving: "50g (~1/2 cup dry)",
    servingGrams: 50,
    calories: 189,
    protein: 6.6,
    carbs: 33.5,
    fat: 3.5,
    fiber: 5.3,
    fdcId: "168878",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-168483",
    name: "Sweet Potato (Baked in Skin)",
    category: "CARB",
    serving: "150g (1 medium)",
    servingGrams: 150,
    calories: 135,
    protein: 3.0,
    carbs: 31.0,
    fat: 0.2,
    fiber: 4.8,
    fdcId: "168483",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-169704",
    name: "Long-Grain Brown Rice (Cooked)",
    category: "CARB",
    serving: "150g (1 cup cooked)",
    servingGrams: 150,
    calories: 184,
    protein: 4.0,
    carbs: 38.6,
    fat: 1.4,
    fiber: 2.7,
    fdcId: "169704",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-168917",
    name: "Quinoa (Cooked)",
    category: "CARB",
    serving: "185g (1 cup cooked)",
    servingGrams: 185,
    calories: 222,
    protein: 8.1,
    carbs: 39.4,
    fat: 3.6,
    fiber: 5.2,
    fdcId: "168917",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-173735",
    name: "Wild Blueberries (Raw)",
    category: "CARB",
    serving: "148g (1 cup)",
    servingGrams: 148,
    calories: 84,
    protein: 1.1,
    carbs: 21.4,
    fat: 0.5,
    fiber: 3.6,
    fdcId: "173735",
    source: "USDA FoodData Central (Foundation)",
  },

  // Fats
  {
    id: "usda-171413",
    name: "Extra Virgin Olive Oil (Cold Pressed)",
    category: "FAT",
    serving: "14g (1 tbsp)",
    servingGrams: 14,
    calories: 119,
    protein: 0.0,
    carbs: 0.0,
    fat: 13.5,
    fiber: 0.0,
    fdcId: "171413",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-171705",
    name: "California Hass Avocado (Raw)",
    category: "FAT",
    serving: "100g (~1/2 avocado)",
    servingGrams: 100,
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    fdcId: "171705",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170567",
    name: "Whole Raw Almonds",
    category: "FAT",
    serving: "28g (1 oz / ~23 kernels)",
    servingGrams: 28,
    calories: 164,
    protein: 6.0,
    carbs: 6.1,
    fat: 14.2,
    fiber: 3.5,
    fdcId: "170567",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170570",
    name: "Natural Peanut Butter (No Added Sugar)",
    category: "FAT",
    serving: "32g (2 tbsp)",
    servingGrams: 32,
    calories: 190,
    protein: 8.0,
    carbs: 7.0,
    fat: 16.0,
    fiber: 2.0,
    fdcId: "170570",
    source: "USDA FoodData Central (SR Legacy)",
  },

  // Vegetables / Micronutrients
  {
    id: "usda-170379",
    name: "Broccoli Florets (Steamed)",
    category: "VEGETABLE",
    serving: "150g (1 cup chopped)",
    servingGrams: 150,
    calories: 52,
    protein: 3.6,
    carbs: 10.1,
    fat: 0.6,
    fiber: 5.1,
    fdcId: "170379",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-169273",
    name: "Baby Spinach (Raw)",
    category: "VEGETABLE",
    serving: "100g (~3 cups)",
    servingGrams: 100,
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    fdcId: "169273",
    source: "USDA FoodData Central (Foundation)",
  },
];
