export interface FoodItem {
  id: string;
  name: string;
  category: "PROTEIN" | "CARB" | "FAT" | "VEGETABLE";
  serving: string;
  servingGrams: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  fdcId?: string;
  source: string;
}

// Comprehensive USDA FoodData Central (Foundation & SR Legacy) Reference Standards
export const USDA_REFERENCE_FOODS: FoodItem[] = [
  // =========================================================================
  // 1. POULTRY & LEAN MEATS
  // =========================================================================
  {
    id: "usda-171077",
    name: "Boneless Skinless Chicken Breast (Cooked, Roasted)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    fiber: 0.0,
    fdcId: "171077",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-171477",
    name: "Chicken Breast (Raw, Boneless Skinless)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 120,
    protein: 22.5,
    carbs: 0.0,
    fat: 2.6,
    fiber: 0.0,
    fdcId: "171477",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-171116",
    name: "Boneless Skinless Chicken Thigh (Cooked, Roasted)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 179,
    protein: 24.7,
    carbs: 0.0,
    fat: 8.2,
    fiber: 0.0,
    fdcId: "171116",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-171115",
    name: "Chicken Thigh with Skin (Cooked, Roasted)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 232,
    protein: 24.0,
    carbs: 0.0,
    fat: 14.5,
    fiber: 0.0,
    fdcId: "171115",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-171114",
    name: "Chicken Thigh (Raw, Meat Only, Skinless)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 119,
    protein: 19.9,
    carbs: 0.0,
    fat: 3.9,
    fiber: 0.0,
    fdcId: "171114",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-171117",
    name: "Chicken Tenderloins (Cooked, Grilled)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 143,
    protein: 29.5,
    carbs: 0.0,
    fat: 2.0,
    fiber: 0.0,
    fdcId: "171117",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-171120",
    name: "Ground Chicken (93% Lean / 7% Fat, Cooked)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 189,
    protein: 23.4,
    carbs: 0.0,
    fat: 10.1,
    fiber: 0.0,
    fdcId: "171120",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-171125",
    name: "Rotisserie Chicken (Breast & Wing Meat, Skinless)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 153,
    protein: 28.0,
    carbs: 0.0,
    fat: 3.9,
    fiber: 0.0,
    fdcId: "171125",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-174036",
    name: "Lean Ground Turkey (93% Lean / 7% Fat, Pan-Broiled)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 195,
    protein: 24.5,
    carbs: 0.0,
    fat: 10.2,
    fiber: 0.0,
    fdcId: "174036",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-174038",
    name: "Extra Lean Ground Turkey (99% Fat Free, Cooked)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 120,
    protein: 28.0,
    carbs: 0.0,
    fat: 1.0,
    fiber: 0.0,
    fdcId: "174038",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-174040",
    name: "Turkey Breast (Cooked, Roasted, Skinless)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 147,
    protein: 30.1,
    carbs: 0.0,
    fat: 2.1,
    fiber: 0.0,
    fdcId: "174040",
    source: "USDA FoodData Central (SR Legacy)",
  },

  // =========================================================================
  // 2. BEEF, BISON & RED MEATS
  // =========================================================================
  {
    id: "usda-170198",
    name: "Top Sirloin Steak (Lean, Cooked, Broiled)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 183,
    protein: 30.6,
    carbs: 0.0,
    fat: 5.9,
    fiber: 0.0,
    fdcId: "170198",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-170200",
    name: "Lean Ground Beef (93% Lean / 7% Fat, Cooked)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 206,
    protein: 26.1,
    carbs: 0.0,
    fat: 10.6,
    fiber: 0.0,
    fdcId: "170200",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170205",
    name: "Extra Lean Ground Beef (96% Lean / 4% Fat, Cooked)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 155,
    protein: 28.0,
    carbs: 0.0,
    fat: 4.5,
    fiber: 0.0,
    fdcId: "170205",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170210",
    name: "Ground Beef (85% Lean / 15% Fat, Cooked)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 250,
    protein: 25.8,
    carbs: 0.0,
    fat: 15.4,
    fiber: 0.0,
    fdcId: "170210",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-170220",
    name: "Filet Mignon / Beef Tenderloin (Cooked, Grilled)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 218,
    protein: 28.2,
    carbs: 0.0,
    fat: 10.9,
    fiber: 0.0,
    fdcId: "170220",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-170225",
    name: "Ribeye Steak (Lip-On, Cooked, Grilled)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 291,
    protein: 24.0,
    carbs: 0.0,
    fat: 21.0,
    fiber: 0.0,
    fdcId: "170225",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-170230",
    name: "Flank Steak (Lean, Cooked, Braised)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 192,
    protein: 28.4,
    carbs: 0.0,
    fat: 8.0,
    fiber: 0.0,
    fdcId: "170230",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-172550",
    name: "Ground Bison (90% Lean, Cooked)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 179,
    protein: 26.6,
    carbs: 0.0,
    fat: 7.3,
    fiber: 0.0,
    fdcId: "172550",
    source: "USDA FoodData Central (Foundation)",
  },

  // =========================================================================
  // 3. SEAFOOD & FISH
  // =========================================================================
  {
    id: "usda-173686",
    name: "Wild Atlantic Salmon (Cooked, Dry Heat)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 182,
    protein: 25.4,
    carbs: 0.0,
    fat: 8.1,
    fiber: 0.0,
    fdcId: "173686",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-173688",
    name: "Farmed Atlantic Salmon (Cooked, Baked)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 206,
    protein: 22.1,
    carbs: 0.0,
    fat: 12.3,
    fiber: 0.0,
    fdcId: "173688",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-173700",
    name: "Canned Light Tuna in Water (Drained)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 116,
    protein: 25.5,
    carbs: 0.0,
    fat: 0.8,
    fiber: 0.0,
    fdcId: "173700",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-173705",
    name: "Yellowfin Tuna Steak (Fresh, Cooked)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 130,
    protein: 29.2,
    carbs: 0.0,
    fat: 0.6,
    fiber: 0.0,
    fdcId: "173705",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-173715",
    name: "Jumbo Shrimp (Cooked, Steamed or Boiled)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 99,
    protein: 24.0,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0.0,
    fdcId: "173715",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-173720",
    name: "Tilapia Fillet (Cooked, Baked)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 128,
    protein: 26.2,
    carbs: 0.0,
    fat: 2.7,
    fiber: 0.0,
    fdcId: "173720",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-173725",
    name: "Atlantic Cod (Cooked, Baked)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 105,
    protein: 22.8,
    carbs: 0.0,
    fat: 0.9,
    fiber: 0.0,
    fdcId: "173725",
    source: "USDA FoodData Central (SR Legacy)",
  },

  // =========================================================================
  // 4. EGGS, DAIRY & VEGETARIAN PROTEINS
  // =========================================================================
  {
    id: "usda-173420",
    name: "Whole Large Egg (Cooked, Hard Boiled)",
    category: "PROTEIN",
    serving: "50g (1 large egg)",
    servingGrams: 50,
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0.0,
    fdcId: "173420",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-173424",
    name: "Egg Whites (Cooked)",
    category: "PROTEIN",
    serving: "100g (~3 large whites)",
    servingGrams: 100,
    calories: 52,
    protein: 10.9,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0.0,
    fdcId: "173424",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-173428",
    name: "Liquid Egg Whites (Pasteurized, Cartoned)",
    category: "PROTEIN",
    serving: "100g (~3 whites)",
    servingGrams: 100,
    calories: 50,
    protein: 10.5,
    carbs: 0.8,
    fat: 0.1,
    fiber: 0.0,
    fdcId: "173428",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170886",
    name: "Nonfat Plain Greek Yogurt (0% Fat)",
    category: "PROTEIN",
    serving: "170g (1 container / 3/4 cup)",
    servingGrams: 170,
    calories: 100,
    protein: 17.3,
    carbs: 6.1,
    fat: 0.7,
    fiber: 0.0,
    fdcId: "170886",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-170890",
    name: "Low-Fat Greek Yogurt (2% Fat, Plain)",
    category: "PROTEIN",
    serving: "170g (3/4 cup)",
    servingGrams: 170,
    calories: 130,
    protein: 16.0,
    carbs: 6.0,
    fat: 3.5,
    fiber: 0.0,
    fdcId: "170890",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170903",
    name: "Low-Fat Cottage Cheese (2% Milkfat)",
    category: "PROTEIN",
    serving: "113g (1/2 cup)",
    servingGrams: 113,
    calories: 90,
    protein: 13.0,
    carbs: 4.5,
    fat: 2.5,
    fiber: 0.0,
    fdcId: "170903",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-170905",
    name: "Fat-Free Cottage Cheese (0% Fat)",
    category: "PROTEIN",
    serving: "113g (1/2 cup)",
    servingGrams: 113,
    calories: 80,
    protein: 14.0,
    carbs: 5.0,
    fat: 0.2,
    fiber: 0.0,
    fdcId: "170905",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-175158",
    name: "Whey Protein Isolate (Standard 90%)",
    category: "PROTEIN",
    serving: "30g (1 scoop)",
    servingGrams: 30,
    calories: 110,
    protein: 25.0,
    carbs: 1.0,
    fat: 0.5,
    fiber: 0.0,
    fdcId: "175158",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-175160",
    name: "Whey Protein Powder (Vanilla / Chocolate, Standard)",
    category: "PROTEIN",
    serving: "32g (1 scoop)",
    servingGrams: 32,
    calories: 125,
    protein: 24.0,
    carbs: 3.0,
    fat: 1.5,
    fiber: 0.5,
    fdcId: "175160",
    source: "USDA FoodData Central (Branded)",
  },
  {
    id: "usda-175165",
    name: "Micellar Casein Protein Powder",
    category: "PROTEIN",
    serving: "34g (1 scoop)",
    servingGrams: 34,
    calories: 120,
    protein: 24.0,
    carbs: 3.0,
    fat: 1.0,
    fiber: 1.0,
    fdcId: "175165",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170875",
    name: "Fairlife Ultra-Filtered Skim Milk",
    category: "PROTEIN",
    serving: "240ml (1 cup)",
    servingGrams: 245,
    calories: 80,
    protein: 13.0,
    carbs: 6.0,
    fat: 0.0,
    fiber: 0.0,
    fdcId: "170875",
    source: "USDA FoodData Central (Branded)",
  },
  {
    id: "usda-172449",
    name: "Extra Firm Tofu (Prepared with Nigari)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 83,
    protein: 10.0,
    carbs: 1.2,
    fat: 5.3,
    fiber: 0.9,
    fdcId: "172449",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-172455",
    name: "Tempeh (Cooked)",
    category: "PROTEIN",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 195,
    protein: 19.9,
    carbs: 7.6,
    fat: 11.4,
    fiber: 4.8,
    fdcId: "172455",
    source: "USDA FoodData Central (Foundation)",
  },

  // =========================================================================
  // 5. COMPLEX CARBOHYDRATES & GRAINS
  // =========================================================================
  {
    id: "usda-168878",
    name: "Rolled Oats (Dry, Whole Grain)",
    category: "CARB",
    serving: "50g (~1/2 cup dry)",
    servingGrams: 50,
    calories: 189,
    protein: 6.6,
    carbs: 33.5,
    fat: 3.5,
    fiber: 5.3,
    fdcId: "168878",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-168880",
    name: "Quick / Instant Oatmeal (Dry, Plain)",
    category: "CARB",
    serving: "40g (1 packet)",
    servingGrams: 40,
    calories: 150,
    protein: 5.0,
    carbs: 27.0,
    fat: 2.5,
    fiber: 4.0,
    fdcId: "168880",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-168885",
    name: "Cream of Rice (Dry Cereal)",
    category: "CARB",
    serving: "45g (1/4 cup dry)",
    servingGrams: 45,
    calories: 170,
    protein: 3.0,
    carbs: 38.0,
    fat: 0.0,
    fiber: 1.0,
    fdcId: "168885",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-169704",
    name: "White Jasmine Rice (Cooked)",
    category: "CARB",
    serving: "150g (1 cup cooked)",
    servingGrams: 150,
    calories: 195,
    protein: 3.8,
    carbs: 43.5,
    fat: 0.4,
    fiber: 0.6,
    fdcId: "169704",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-169706",
    name: "White Basmati Rice (Cooked)",
    category: "CARB",
    serving: "150g (1 cup cooked)",
    servingGrams: 150,
    calories: 180,
    protein: 4.0,
    carbs: 39.0,
    fat: 0.5,
    fiber: 0.8,
    fdcId: "169706",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-169708",
    name: "Long-Grain Brown Rice (Cooked)",
    category: "CARB",
    serving: "150g (1 cup cooked)",
    servingGrams: 150,
    calories: 184,
    protein: 4.0,
    carbs: 38.6,
    fat: 1.4,
    fiber: 2.7,
    fdcId: "169708",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-168483",
    name: "Sweet Potato (Baked in Skin)",
    category: "CARB",
    serving: "150g (1 medium)",
    servingGrams: 150,
    calories: 135,
    protein: 3.0,
    carbs: 31.0,
    fat: 0.2,
    fiber: 4.8,
    fdcId: "168483",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-168485",
    name: "Russet Potato (Baked, Flesh & Skin)",
    category: "CARB",
    serving: "173g (1 medium)",
    servingGrams: 173,
    calories: 164,
    protein: 4.3,
    carbs: 37.0,
    fat: 0.2,
    fiber: 4.0,
    fdcId: "168485",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-168917",
    name: "Quinoa (Cooked)",
    category: "CARB",
    serving: "185g (1 cup cooked)",
    servingGrams: 185,
    calories: 222,
    protein: 8.1,
    carbs: 39.4,
    fat: 3.6,
    fiber: 5.2,
    fdcId: "168917",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-168925",
    name: "Whole Wheat Pasta (Cooked)",
    category: "CARB",
    serving: "140g (1 cup cooked)",
    servingGrams: 140,
    calories: 174,
    protein: 7.5,
    carbs: 37.2,
    fat: 0.8,
    fiber: 4.6,
    fdcId: "168925",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-168930",
    name: "White Enriched Pasta (Cooked)",
    category: "CARB",
    serving: "140g (1 cup cooked)",
    servingGrams: 140,
    calories: 220,
    protein: 8.0,
    carbs: 43.0,
    fat: 1.3,
    fiber: 2.5,
    fdcId: "168930",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-169000",
    name: "Ezekiel 4:9 Sprouted Whole Grain Bread",
    category: "CARB",
    serving: "34g (1 slice)",
    servingGrams: 34,
    calories: 80,
    protein: 5.0,
    carbs: 15.0,
    fat: 0.5,
    fiber: 3.0,
    fdcId: "169000",
    source: "USDA FoodData Central (Branded)",
  },
  {
    id: "usda-169005",
    name: "Plain White Sourdough Bread",
    category: "CARB",
    serving: "50g (1 thick slice)",
    servingGrams: 50,
    calories: 120,
    protein: 4.5,
    carbs: 23.0,
    fat: 0.8,
    fiber: 1.2,
    fdcId: "169005",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-169010",
    name: "Plain White Bagel",
    category: "CARB",
    serving: "105g (1 standard bagel)",
    servingGrams: 105,
    calories: 280,
    protein: 11.0,
    carbs: 56.0,
    fat: 1.5,
    fiber: 2.5,
    fdcId: "169010",
    source: "USDA FoodData Central (Foundation)",
  },

  // =========================================================================
  // 6. HEALTHY FATS, NUTS & OILS
  // =========================================================================
  {
    id: "usda-171413",
    name: "Extra Virgin Olive Oil (Cold Pressed)",
    category: "FAT",
    serving: "14g (1 tbsp)",
    servingGrams: 14,
    calories: 119,
    protein: 0.0,
    carbs: 0.0,
    fat: 13.5,
    fiber: 0.0,
    fdcId: "171413",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-171705",
    name: "California Hass Avocado (Raw)",
    category: "FAT",
    serving: "100g (~1/2 avocado)",
    servingGrams: 100,
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    fdcId: "171705",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170567",
    name: "Whole Raw Almonds",
    category: "FAT",
    serving: "28g (1 oz / ~23 kernels)",
    servingGrams: 28,
    calories: 164,
    protein: 6.0,
    carbs: 6.1,
    fat: 14.2,
    fiber: 3.5,
    fdcId: "170567",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170570",
    name: "Natural Peanut Butter (No Added Sugar)",
    category: "FAT",
    serving: "32g (2 tbsp)",
    servingGrams: 32,
    calories: 190,
    protein: 8.0,
    carbs: 7.0,
    fat: 16.0,
    fiber: 2.0,
    fdcId: "170570",
    source: "USDA FoodData Central (SR Legacy)",
  },
  {
    id: "usda-170575",
    name: "Creamy Almond Butter (No Salt)",
    category: "FAT",
    serving: "32g (2 tbsp)",
    servingGrams: 32,
    calories: 196,
    protein: 7.0,
    carbs: 6.0,
    fat: 17.8,
    fiber: 3.3,
    fdcId: "170575",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170580",
    name: "Raw English Walnuts (Halves)",
    category: "FAT",
    serving: "28g (1 oz / 14 halves)",
    servingGrams: 28,
    calories: 185,
    protein: 4.3,
    carbs: 3.9,
    fat: 18.5,
    fiber: 1.9,
    fdcId: "170580",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170585",
    name: "Chia Seeds (Black, Dried)",
    category: "FAT",
    serving: "28g (2 tbsp)",
    servingGrams: 28,
    calories: 138,
    protein: 4.7,
    carbs: 11.9,
    fat: 8.7,
    fiber: 9.8,
    fdcId: "170585",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170590",
    name: "Grass-Fed Butter (Salted or Unsalted)",
    category: "FAT",
    serving: "14g (1 tbsp)",
    servingGrams: 14,
    calories: 102,
    protein: 0.1,
    carbs: 0.0,
    fat: 11.5,
    fiber: 0.0,
    fdcId: "170590",
    source: "USDA FoodData Central (Foundation)",
  },

  // =========================================================================
  // 7. FRUITS & BERRIES
  // =========================================================================
  {
    id: "usda-173735",
    name: "Wild Blueberries (Fresh Raw)",
    category: "CARB",
    serving: "148g (1 cup)",
    servingGrams: 148,
    calories: 84,
    protein: 1.1,
    carbs: 21.4,
    fat: 0.5,
    fiber: 3.6,
    fdcId: "173735",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-173740",
    name: "Fresh Strawberries (Raw)",
    category: "CARB",
    serving: "150g (1 cup halves)",
    servingGrams: 150,
    calories: 49,
    protein: 1.0,
    carbs: 11.7,
    fat: 0.5,
    fiber: 3.0,
    fdcId: "173740",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-173745",
    name: "Fresh Banana (Medium, Raw)",
    category: "CARB",
    serving: "118g (1 medium)",
    servingGrams: 118,
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.3,
    fiber: 3.1,
    fdcId: "173745",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-173750",
    name: "Honeycrisp Apple (Raw with Skin)",
    category: "CARB",
    serving: "182g (1 medium)",
    servingGrams: 182,
    calories: 95,
    protein: 0.5,
    carbs: 25.0,
    fat: 0.3,
    fiber: 4.4,
    fdcId: "173750",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-173755",
    name: "Fresh Raspberries (Raw)",
    category: "CARB",
    serving: "123g (1 cup)",
    servingGrams: 123,
    calories: 64,
    protein: 1.5,
    carbs: 14.7,
    fat: 0.8,
    fiber: 8.0,
    fdcId: "173755",
    source: "USDA FoodData Central (Foundation)",
  },

  // =========================================================================
  // 8. VEGETABLES & FIBER SOURCES
  // =========================================================================
  {
    id: "usda-170379",
    name: "Broccoli Florets (Steamed)",
    category: "VEGETABLE",
    serving: "150g (1 cup chopped)",
    servingGrams: 150,
    calories: 52,
    protein: 3.6,
    carbs: 10.1,
    fat: 0.6,
    fiber: 5.1,
    fdcId: "170379",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-169273",
    name: "Baby Spinach (Fresh Raw)",
    category: "VEGETABLE",
    serving: "100g (~3 cups)",
    servingGrams: 100,
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    fdcId: "169273",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170385",
    name: "Fresh Asparagus (Cooked, Boiled)",
    category: "VEGETABLE",
    serving: "100g (~6 spears)",
    servingGrams: 100,
    calories: 22,
    protein: 2.4,
    carbs: 4.1,
    fat: 0.2,
    fiber: 2.0,
    fdcId: "170385",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170390",
    name: "Green Beans / Haricots Verts (Steamed)",
    category: "VEGETABLE",
    serving: "100g (3.5 oz)",
    servingGrams: 100,
    calories: 35,
    protein: 1.9,
    carbs: 7.9,
    fat: 0.3,
    fiber: 3.2,
    fdcId: "170390",
    source: "USDA FoodData Central (Foundation)",
  },
  {
    id: "usda-170395",
    name: "Zucchini Squash (Cooked, Sliced)",
    category: "VEGETABLE",
    serving: "150g (1 cup)",
    servingGrams: 150,
    calories: 27,
    protein: 2.1,
    carbs: 4.8,
    fat: 0.5,
    fiber: 1.8,
    fdcId: "170395",
    source: "USDA FoodData Central (Foundation)",
  },
];
